version: '2'
services:
    rabbitmq:
        image: rabbitmq:3-management
        ports:
            - '5672:5672'
            - '15672:15672'
        networks:
            - my-own-network 

    mongo:
        image: mongo:latest
        volumes: 
            - /data/db:/data/db
        ports:
            - "27018:27018"
        networks:
            - my-own-network    

    distance:
        build: ./Distance
        restart: always
        ports:
            - '9091:9091'
        depends_on:
            - rabbitmq
        networks:
            - my-own-network
            
    api_gateway: 
        build: ../ApiGateway
        restart: always
        ports:
            - '3000:3000'
        depends_on:
            - rabbitmq
        networks:
            - my-own-network    

            
    crosswalk: 
        build: ./Crosswalks
        restart: always
        ports:
            - '3002:3002'
        depends_on:
            - rabbitmq
            - mongo
        networks:
            - my-own-network    

            



networks:
    my-own-network:
        driver: bridge


